version: "3"
services:
  backend:
    container_name: rg-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 4444:4444
    volumes:
      - ./:/backend
      - /backend/node_modules
